# Monitor layout copied from the current KDE display configuration.
output DP-3 {
    mode 3440x1440@99.98Hz
    pos 0 0
    scale 1.25
}

output HDMI-A-1 {
    mode 3840x2160@120Hz
    pos 2752 1152
    scale 2
}

output DP-2 {
    mode 1920x1080@240Hz
    pos 2752 72
    scale 1
}

output DP-1 {
    mode 3440x1440@99.98Hz
    pos 0 1152
    scale 1.25
}